version: 0.0
os: linux
#files:
#  - source: Config/config.txt
#    destination: /webapps/Config
#  - source: source
#    destination: /webapps/myApp
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 100
  ApplicationStart:
    - location: start_server.sh
      timeout: 100
