version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - cd lambda_functions\FileProcessor
      - zip function.zip lambda_function.py
  post-build:
    commands:
      - aws lambda update-function-code --function-name my-function --zip-file fileb://function.zip
