version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - cd sam-app
  build:
    commands:
      - sam build
      - pwd
      - ls
  post_build:
    commands:
      - cd .aws-sam
      - pwd
      - ls
      - cd build
      - pwd
      - ls

artifacts:
  base-directory: sam-app/.aws-sam
  files: "*/**"
