version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - cd sam-app
  build:
    commands:
      - sam build
artifacts:
  basedir: sam-app/.aws-sam
  files: "*/**"
