version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - mvn test
  build:
    commands:
      - mvn sonar:sonar -Dsonar.projectKey=cnsd08-backend -Dsonar.host.url=https://sonarqube.cloud-native-minor.it -Dsonar.login=$SONAR_TOKEN
