version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - cd sam-app
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam deploy

artifacts:
  base-directory: sam-app/.aws-sam
  files: "**/*"
