version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "notes-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-az2czols77zf"
s3_prefix = "notes-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
