AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notes-app

  Sample SAM Template for notes-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.8
    Handler: lambda_function.lambda_handler
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  GetAllNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_all_notes/
      Events:
        NotesApi:
          Type: Api
          Properties:
            Path: /notes
            Method: get

  GetNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_note/
      Events:
        NotesApi:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: get

  CreateNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/create_note/
      Events:
        NotesApi:
          Type: Api
          Properties:
            Path: /notes
            Method: post

  DeleteNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/delete_note/
      Events:
        NotesApi:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: delete


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
